version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  rspec:
    working_directory: ~/find_craft_beer
    docker:
      - image: cimg/ruby:3.1.2
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Start containers and verify it is workingj
          command: |
            set -x
            docker-compose up -d
      - run:
          name: Setup database
          command: |
            docker-compose run web rails db:create db:migrate
      - run:
          name: Run rspec
          command: docker-compose run web rspec
  heroku_deploy:
    working_directory: ~/find_craft_beer
    executor: heroku/default
    resource_class: small
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
      - run:
          name: Run post-deploy tasks
          command: |
            heroku run bin/rails db:migrate -a $HEROKU_APP_NAME

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - rspec
      - heroku_deploy:
          requires:
            - rspec
          filters:
            branches:
              only: master
